version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: thatsbass/piral:v1
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"